#"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[git_metrics]
disabled = false

[directory]
style = "bold blue"
read_only = " "
truncation_length = 3
truncate_to_repo = true

[git_branch]
style = "bold blue"

[character]
success_symbol = "[λ](bold blue)"
error_symbol = "[λ](bold red)"

[memory_usage]
symbol = " "

[aws]
disabled = true

